openapi: 3.0.3
info:
  title: Workflow API
  version: 1.0.0
paths:
  /api/v1/{organizationId}/workflows:
    post:
      summary: Create a new workflow
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      responses:
        '200':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
      security:
        - bearerAuth: []
      # You can also specify headers explicitly if needed:
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer access token
        - name: Accept
          in: header
          required: false
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            default: application/json
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Workflow:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        organizationId:
          type: string
        activities:
          type: array
          items:
            type: object
        transitions:
          type: array
          items:
            type: object
        variables:
          type: array
          items:
            type: object
        diagram:
          type: object
        coreInformation:
          type: object
        lastUpdated:
          type: string
          format: date-time
        ownerId:
          type: string
        published:
          type: boolean
      required:
        - name
        - activities
        - transitions
        - variables
        - diagram
